version: '3.7'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    networks:
      - monitoring
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml      
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - influxdb

  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./k6:/k6
    working_dir: /k6
    command: ["run", "--out", "influxdb=http://influxdb:8086/k6", "/k6/test.js"]
    networks:
      - monitoring
    depends_on:
      - influxdb



volumes:
  grafana-data:
  influxdb-data:


networks:
  monitoring:
